

# nw.toml - for additional properties please see https://github.com/aspectron/cargo-nw

[application]
name = "nw-sys-example"
version = "0.1.0"
title = "Nw sys example"
organization = "Your Organization Name"

[description]
short = "..."
long = """
...
""""

[package]
# root = ""
# resources = "resources/setup"
# exclude = ["resources/setup"]
exclude = [{ glob = ["{src/*,target/*,test/*,resources/setup/*,*.lock,*.toml,.git*,analyzer-target/*}"] }]

[node-webkit]
version = "0.71.0"
ffmpeg = false

# [dmg]
# window = ["0,0,300,300"]
# icon = ["0,0"]
# applications = ["0,0"]

[windows]
uuid = "bef64e00-b25f-480b-a081-4f47468b5017"
group = "$GROUP"
# run_on_startup = "everyone"
run_after_setup = true

# [languages]
# languages = ["english"]

# [firewall]
# application = "in:out"

